### PR TITLE
SSL verifier fix

### PR DESCRIPTION
**Pull request by yousafsyed**
I have added the method to specify the certificate file. ie (PEM). I
have added a working example to the test folder along with the
certificate. You can verify it and also you can download the ssl
certifcate from firefox for any website that offers ssl and when saving
save it as .pem file instead of .crt and choose the option to download
with chain.

### CODE REVIEW

**Comment by ahmadnassri** [comment]
@yousafsyed I just released v2.0.0 can you please review and refactor your changes accordingly? 

also, some more unit-tests (with phpunit style) would be great!

thank you!

**Comment by ahmadnassri** [comment]
hey @yousafsyed, any progress? 

thanks :)

**Comment by kamaljeetrathi** [comment]
How to set pem files in unirest request.

**Comment by ahmadnassri** [comment]
@kamaljeetrathi please open a ticket on the [unirest-java](/Mashape/unirest-java) project

**Pull request closed without merging**
